import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google"; ← 아직 지원되지 않음 (또는 설치 필요)
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className="antialiased">
        {children}
        </body>
        </html>
    );
}
